# MongoDB ba?lant?s?
spring.data.mongodb.uri=mongodb://localhost:27017/jwtdb

# Sunucu portu
server.port=8080

# Thymeleaf yap?land?rmas? (Opsiyonel)
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html